### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by mickel8** [elixir-webrtc/xav#1]
* [x] - one pkt can containe multiple frames
* [x] - pkt frame unref
* [x] - nif and ffmpeg code split up
* [x] - resource cleanup
* [x] - seeking
* [x] - tests
* [x] - README
* [ ] - streams
* [x] - camera input 
* [x] - CI for linux
* [x] - CI for mac
* [x] - C debug logs
* [x] - handle EOF 
* ~handle ffmpeg binaries~
* [x] - audio support
* [x] - examples
* [ ] - network based streams
